name: Development builds

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      
      - name: Bump manifest version
        run: |
          sed -i "s/\"version\": \"\(.*\)\",/\"version\": \"\1.$(date +%s)\"/g" manifest.json

      - name: Build and sign Firefox Extension
        run: |
          npx web-ext sign --channel=unlisted --api-key=${{ secrets.JWT_ISSUER }} --api-secret=${{ secrets.JWT_SECRET }}
          mv web-ext-artifacts/nofeed*.xpi nofeed.xpi
        
      - name: Create prerelease
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: prerelease
          release_name: Prerelease
          draft: false
          prerelease: true
      
      - name: Upload prerelease Firefox Extension
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nofeed.xpi
          asset_name: nofeed.xpi
          asset_content_type: application/x-xpinstall
